// src/components/events/EventLogisticsChecklist.tsx
import React, { useState, useEffect } from "react";
import { toast } from "sonner";
import {
  CheckCircle2,
  Clock,
  AlertTriangle,
  Plus,
  UserCheck,
  ShieldAlert,
  Sparkles,
  User,
  Trash2,
  Calendar,
  Check,
  RefreshCw,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { EventTask, TaskStatus } from "@/types/eventLogistics";
import { EventLogisticsService } from "@/services/eventLogisticsService";
import { createClient } from "@/lib/supabase/client";

interface EventLogisticsChecklistProps {
  eventId: string;
  clubId?: string | null;
  eventData?: any;
}

export function EventLogisticsChecklist({
  eventId,
  clubId,
  eventData,
}: EventLogisticsChecklistProps) {
  const [tasks, setTasks] = useState<EventTask[]>([]);
  const [clubExecs, setClubExecs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);

  // New custom task form state
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newDueDate, setNewDueDate] = useState("");
  const [newAssigneeId, setNewAssigneeId] = useState("");
  const [newIsCritical, setNewIsCritical] = useState(false);
  const [creating, setCreating] = useState(false);

  const supabase = createClient();

  useEffect(() => {
    async function loadLogisticsData() {
      setLoading(true);

      try {
        // Sync auto-generated tasks if eventData provided
        let currentTasks: EventTask[] = [];
        if (eventData) {
          currentTasks = await EventLogisticsService.syncAutoGeneratedTasks(eventId, eventData);
        } else {
          currentTasks = await EventLogisticsService.getEventTasks(eventId);
        }

        setTasks(currentTasks);

        // Fetch club executive members for assignee selection
        if (clubId) {
          const { data: members } = await supabase
            .from("club_members")
            .select(`
              user_id,
              role,
              profiles:user_id ( id, first_name, last_name, handle )
            `)
            .eq("club_id", clubId)
            .eq("status", "approved");

          if (members) {
            setClubExecs(
              members.map((m: any) => ({
                id: m.user_id,
                name: m.profiles
                  ? `${m.profiles.first_name || ""} ${m.profiles.last_name || ""}`.trim() || m.profiles.handle
                  : "Executive",
                role: m.role,
              }))
            );
          }
        }
      } catch (err) {
        console.error("Failed to load logistics checklist data:", err);
      } finally {
        setLoading(false);
      }
    }

    loadLogisticsData();
  }, [eventId, clubId, eventData]);

  const handleStatusChange = async (taskId: string, newStatus: TaskStatus) => {
    try {
      await EventLogisticsService.updateTaskStatus(taskId, newStatus);
      setTasks((prev) =>
        prev.map((t) => (t.id === taskId ? { ...t, status: newStatus } : t))
      );
      toast.success(`Task status updated to ${newStatus.replace("_", " ")}`);
    } catch (err: any) {
      toast.error(err.message || "Failed to update task status.");
    }
  };

  const handleAssigneeChange = async (taskId: string, assigneeId: string) => {
    try {
      const selectedId = assigneeId || null;
      await EventLogisticsService.assignTask(taskId, selectedId);

      const assignedExec = clubExecs.find((e) => e.id === selectedId);
      setTasks((prev) =>
        prev.map((t) =>
          t.id === taskId
            ? {
                ...t,
                assignee_id: selectedId,
                assignee: assignedExec
                  ? { id: assignedExec.id, first_name: assignedExec.name }
                  : null,
              }
            : t
        )
      );
      toast.success("Task assignee updated.");
    } catch (err: any) {
      toast.error(err.message || "Failed to assign task.");
    }
  };

  const handleCreateCustomTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) {
      toast.error("Task title is required.");
      return;
    }

    try {
      setCreating(true);
      const newTask = await EventLogisticsService.createCustomTask({
        eventId,
        title: newTitle,
        description: newDesc,
        dueDate: newDueDate || undefined,
        assigneeId: newAssigneeId || undefined,
        isCritical: newIsCritical,
      });

      setTasks((prev) => [newTask, ...prev]);
      setIsAddModalOpen(false);
      setNewTitle("");
      setNewDesc("");
      setNewDueDate("");
      setNewAssigneeId("");
      setNewIsCritical(false);
      toast.success("Custom task added to checklist.");
    } catch (err: any) {
      toast.error(err.message || "Failed to create task.");
    } finally {
      setCreating(false);
    }
  };

  const handleDeleteTask = async (taskId: string) => {
    if (!window.confirm("Delete this logistics task?")) return;

    try {
      await EventLogisticsService.deleteTask(taskId);
      setTasks((prev) => prev.filter((t) => t.id !== taskId));
      toast.success("Task deleted.");
    } catch (err: any) {
      toast.error(err.message || "Failed to delete task.");
    }
  };

  // Critical tasks status for publication guard
  const incompleteCriticalTasks = tasks.filter((t) => t.is_critical && t.status !== "done");

  const todoTasks = tasks.filter((t) => t.status === "todo");
  const inProgressTasks = tasks.filter((t) => t.status === "in_progress");
  const doneTasks = tasks.filter((t) => t.status === "done");

  if (loading) {
    return (
      <div className="neu-border p-6 bg-white dark:bg-zinc-900 flex items-center justify-center gap-3">
        <RefreshCw className="h-5 w-5 animate-spin text-black dark:text-white" />
        <span className="font-mono text-xs">Loading logistics checklist…</span>
      </div>
    );
  }

  return (
    <section aria-label="Event Logistics Checklist" className="space-y-6">
      {/* Publication Guard Banner */}
      {incompleteCriticalTasks.length > 0 ? (
        <div className="flex items-center gap-3 p-4 bg-amber-100 border-2 border-amber-800 text-amber-950 font-mono text-xs shadow-[2px_2px_0px_rgba(0,0,0,1)]">
          <ShieldAlert className="h-6 w-6 shrink-0 text-red-600" />
          <div>
            <p className="font-bold uppercase">
              Publication Guard Active ({incompleteCriticalTasks.length} Critical Task
              {incompleteCriticalTasks.length > 1 ? "s" : ""} Pending)
            </p>
            <p className="text-[11px] mt-0.5 opacity-90">
              Event cannot be published to the public feed until all critical security & approval
              tasks are marked <strong>Done</strong>.
            </p>
          </div>
        </div>
      ) : (
        <div className="flex items-center gap-3 p-4 bg-green-100 border-2 border-green-800 text-green-950 font-mono text-xs shadow-[2px_2px_0px_rgba(0,0,0,1)]">
          <CheckCircle2 className="h-6 w-6 shrink-0 text-green-700" />
          <div>
            <p className="font-bold uppercase">Publication Ready</p>
            <p className="text-[11px] mt-0.5 opacity-90">
              All critical logistics tasks are completed! Event is eligible for public release.
            </p>
          </div>
        </div>
      )}

      {/* Header & Add Custom Task Button */}
      <div className="flex items-center justify-between flex-wrap gap-4 neu-border p-4 bg-white dark:bg-zinc-900">
        <div>
          <h3 className="font-display text-lg font-bold uppercase tracking-tight text-black dark:text-white flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-amber-500" /> Event Logistics Checklist
          </h3>
          <p className="font-mono text-xs text-gray-500 mt-0.5">
            Auto-generated and custom tasks to ensure seamless event execution.
          </p>
        </div>

        <Button
          onClick={() => setIsAddModalOpen(true)}
          className="neu-border bg-black text-white hover:bg-zinc-800 font-mono text-xs font-bold uppercase"
        >
          <Plus className="h-4 w-4 mr-1" /> Add Custom Task
        </Button>
      </div>

      {/* Kanban / Task Columns */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Column: To Do */}
        <div className="neu-border bg-gray-50 dark:bg-zinc-900 p-4 space-y-3">
          <div className="flex items-center justify-between border-b-2 border-black pb-2">
            <span className="font-mono text-xs font-bold uppercase flex items-center gap-1.5">
              <Clock className="h-4 w-4 text-amber-600" /> To Do ({todoTasks.length})
            </span>
          </div>

          <div className="space-y-3 min-h-[150px]">
            {todoTasks.map((t) => (
              <TaskCard
                key={t.id}
                task={t}
                execs={clubExecs}
                onStatusChange={handleStatusChange}
                onAssigneeChange={handleAssigneeChange}
                onDelete={handleDeleteTask}
              />
            ))}
          </div>
        </div>

        {/* Column: In Progress */}
        <div className="neu-border bg-gray-50 dark:bg-zinc-900 p-4 space-y-3">
          <div className="flex items-center justify-between border-b-2 border-black pb-2">
            <span className="font-mono text-xs font-bold uppercase flex items-center gap-1.5">
              <RefreshCw className="h-4 w-4 text-blue-600 animate-spin" /> In Progress (
              {inProgressTasks.length})
            </span>
          </div>

          <div className="space-y-3 min-h-[150px]">
            {inProgressTasks.map((t) => (
              <TaskCard
                key={t.id}
                task={t}
                execs={clubExecs}
                onStatusChange={handleStatusChange}
                onAssigneeChange={handleAssigneeChange}
                onDelete={handleDeleteTask}
              />
            ))}
          </div>
        </div>

        {/* Column: Done */}
        <div className="neu-border bg-gray-50 dark:bg-zinc-900 p-4 space-y-3">
          <div className="flex items-center justify-between border-b-2 border-black pb-2">
            <span className="font-mono text-xs font-bold uppercase flex items-center gap-1.5">
              <CheckCircle2 className="h-4 w-4 text-green-600" /> Done ({doneTasks.length})
            </span>
          </div>

          <div className="space-y-3 min-h-[150px]">
            {doneTasks.map((t) => (
              <TaskCard
                key={t.id}
                task={t}
                execs={clubExecs}
                onStatusChange={handleStatusChange}
                onAssigneeChange={handleAssigneeChange}
                onDelete={handleDeleteTask}
              />
            ))}
          </div>
        </div>
      </div>

      {/* Add Custom Task Dialog */}
      <Dialog open={isAddModalOpen} onOpenChange={setIsAddModalOpen}>
        <DialogContent className="neu-border bg-white dark:bg-zinc-900 max-w-md">
          <DialogHeader>
            <DialogTitle className="font-display text-lg uppercase font-bold">
              Add Custom Logistics Task
            </DialogTitle>
            <DialogDescription className="font-mono text-xs text-gray-500">
              Create a custom task for your event team.
            </DialogDescription>
          </DialogHeader>

          <form onSubmit={handleCreateCustomTask} className="space-y-4 font-mono text-xs">
            <div>
              <label className="block font-bold mb-1">Task Title *</label>
              <Input
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="e.g. Order Name Badges & Lanyards"
                required
              />
            </div>

            <div>
              <label className="block font-bold mb-1">Description</label>
              <Textarea
                value={newDesc}
                onChange={(e) => setNewDesc(e.target.value)}
                placeholder="Details or instructions for the assignee..."
                rows={3}
              />
            </div>

            <div>
              <label className="block font-bold mb-1">Due Date</label>
              <Input
                type="datetime-local"
                value={newDueDate}
                onChange={(e) => setNewDueDate(e.target.value)}
              />
            </div>

            <div>
              <label className="block font-bold mb-1">Assign Executive</label>
              <select
                value={newAssigneeId}
                onChange={(e) => setNewAssigneeId(e.target.value)}
                className="w-full p-2 neu-border bg-white dark:bg-zinc-800 text-black dark:text-white"
              >
                <option value="">Unassigned</option>
                {clubExecs.map((exec) => (
                  <option key={exec.id} value={exec.id}>
                    {exec.name} ({exec.role})
                  </option>
                ))}
              </select>
            </div>

            <label className="flex items-center gap-2 cursor-pointer font-bold">
              <input
                type="checkbox"
                checked={newIsCritical}
                onChange={(e) => setNewIsCritical(e.target.checked)}
                className="h-4 w-4 accent-black border-2 border-black"
              />
              <span className="text-red-600">Critical Task (Blocks Public Event Release)</span>
            </label>

            <DialogFooter>
              <Button
                type="button"
                variant="outline"
                onClick={() => setIsAddModalOpen(false)}
                className="neu-border"
              >
                Cancel
              </Button>
              <Button
                type="submit"
                disabled={creating}
                className="neu-border bg-black text-white hover:bg-zinc-800 font-bold uppercase"
              >
                {creating ? "Creating…" : "Save Task"}
              </Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </section>
  );
}

function TaskCard({
  task,
  execs,
  onStatusChange,
  onAssigneeChange,
  onDelete,
}: {
  task: EventTask;
  execs: any[];
  onStatusChange: (id: string, s: TaskStatus) => void;
  onAssigneeChange: (id: string, assigneeId: string) => void;
  onDelete: (id: string) => void;
}) {
  const isOverdue =
    task.due_date && task.status !== "done"
      ? new Date().getTime() > new Date(task.due_date).getTime()
      : false;

  return (
    <div
      className={`neu-border p-3.5 bg-white dark:bg-zinc-800 space-y-2.5 shadow-[2px_2px_0px_rgba(0,0,0,1)] ${
        isOverdue ? "border-red-600 bg-red-50/30" : ""
      }`}
    >
      {/* Badges */}
      <div className="flex items-center justify-between gap-2 flex-wrap">
        <div className="flex items-center gap-1.5 flex-wrap">
          {task.is_critical && (
            <span className="font-mono text-[9px] font-bold uppercase px-1.5 py-0.5 bg-red-100 text-red-800 border border-red-600">
              🛡️ Blocks Release
            </span>
          )}
          {task.is_auto_generated ? (
            <span className="font-mono text-[9px] font-bold uppercase px-1.5 py-0.5 bg-amber-100 text-amber-800 border border-amber-600">
              ⚡ Auto Rule
            </span>
          ) : (
            <span className="font-mono text-[9px] font-bold uppercase px-1.5 py-0.5 bg-blue-100 text-blue-800 border border-blue-600">
              👤 Custom
            </span>
          )}
        </div>

        {!task.is_auto_generated && (
          <button
            onClick={() => onDelete(task.id)}
            title="Delete task"
            className="text-gray-400 hover:text-red-600 transition-colors"
          >
            <Trash2 size={13} />
          </button>
        )}
      </div>

      {/* Title & Desc */}
      <div>
        <h4 className="font-mono text-xs font-bold text-black dark:text-white leading-snug">
          {task.title}
        </h4>
        {task.description && (
          <p className="font-mono text-[11px] text-gray-600 dark:text-gray-400 mt-1">
            {task.description}
          </p>
        )}
      </div>

      {/* Due Date & Overdue warning */}
      {task.due_date && (
        <div
          className={`flex items-center gap-1 font-mono text-[10px] ${
            isOverdue ? "text-red-600 font-bold" : "text-gray-500"
          }`}
        >
          <Calendar size={11} />
          <span>Due: {new Date(task.due_date).toLocaleDateString()}</span>
          {isOverdue && <span className="uppercase text-[9px]">(Overdue)</span>}
        </div>
      )}

      {/* Assignee Selector */}
      <div className="flex items-center gap-1.5 pt-1 border-t border-black/10">
        <User size={12} className="text-gray-400 shrink-0" />
        <select
          value={task.assignee_id || ""}
          onChange={(e) => onAssigneeChange(task.id, e.target.value)}
          className="font-mono text-[10px] bg-transparent border-none p-0 font-semibold cursor-pointer text-gray-700 dark:text-gray-300 hover:text-black focus:outline-none"
        >
          <option value="">Unassigned</option>
          {execs.map((exec) => (
            <option key={exec.id} value={exec.id}>
              {exec.name}
            </option>
          ))}
        </select>
      </div>

      {/* Status Buttons */}
      <div className="flex gap-1.5 pt-1">
        {task.status !== "todo" && (
          <button
            onClick={() => onStatusChange(task.id, "todo")}
            className="font-mono text-[9px] font-bold uppercase px-2 py-1 neu-border bg-gray-100 hover:bg-gray-200"
          >
            To Do
          </button>
        )}
        {task.status !== "in_progress" && (
          <button
            onClick={() => onStatusChange(task.id, "in_progress")}
            className="font-mono text-[9px] font-bold uppercase px-2 py-1 neu-border bg-blue-100 text-blue-900 hover:bg-blue-200"
          >
            In Progress
          </button>
        )}
        {task.status !== "done" && (
          <button
            onClick={() => onStatusChange(task.id, "done")}
            className="font-mono text-[9px] font-bold uppercase px-2 py-1 neu-border bg-green-100 text-green-900 hover:bg-green-200"
          >
            Done
          </button>
        )}
      </div>
    </div>
  );
}
