// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/security/ReentrancyGuard.sol";

// Minimal Aave V3 Pool Interface
interface IPool {
    function supply(address asset, uint256 amount, address onBehalfOf, uint16 referralCode) external;
    function withdraw(address asset, uint256 amount, address to) external returns (uint256);
}

// Minimal AToken Interface (aUSDC)
interface IAToken is IERC20 {
    function scaledBalanceOf(address user) external view returns (uint256);
}

/**
 * @title LosslessYieldDonation
 * @dev A smart contract allowing High-Net-Worth individuals to donate via DeFi Yield routing.
 * The donor deposits USDC which is routed into Aave V3 to earn yield.
 * The principal is structurally protected and strictly claimable ONLY by the donor.
 * All generated yield (aUSDC growth) is claimable by the designated Club Treasury.
 */
contract LosslessYieldDonation is ReentrancyGuard {
    IERC20 public immutable usdcToken;
    IAToken public immutable aUsdcToken;
    IPool public immutable aavePool;

    address public immutable donorWallet;
    address public immutable clubTreasuryWallet;
    
    uint256 public principalAmount;

    event PrincipalDeposited(address indexed donor, uint256 amount);
    event PrincipalWithdrawn(address indexed donor, uint256 amount);
    event YieldHarvested(address indexed club, uint256 amount);

    /**
     * @param _usdcAddress The Polygon USDC token address
     * @param _aUsdcAddress The Aave V3 aUSDC token address
     * @param _aavePoolAddress The Aave V3 Pool contract address
     * @param _donorWallet The absolute owner of the principal capital
     * @param _clubTreasuryWallet The recipient of the generated APY yield
     */
    constructor(
        address _usdcAddress, 
        address _aUsdcAddress, 
        address _aavePoolAddress, 
        address _donorWallet, 
        address _clubTreasuryWallet
    ) {
        usdcToken = IERC20(_usdcAddress);
        aUsdcToken = IAToken(_aUsdcAddress);
        aavePool = IPool(_aavePoolAddress);
        donorWallet = _donorWallet;
        clubTreasuryWallet = _clubTreasuryWallet;
    }

    modifier onlyDonor() {
        require(msg.sender == donorWallet, "Unauthorized: Only Donor can access principal.");
        _;
    }

    /**
     * @dev Donor deposits USDC into this contract, which instantly supplies it to Aave V3.
     */
    function depositPrincipal(uint256 _amount) external onlyDonor nonReentrant {
        require(_amount > 0, "Cannot deposit 0");
        
        // Transfer USDC from Donor to this Contract
        require(usdcToken.transferFrom(msg.sender, address(this), _amount), "USDC transfer failed");

        // Approve Aave Pool to spend USDC
        require(usdcToken.approve(address(aavePool), _amount), "Aave approve failed");

        // Supply USDC to Aave to start earning yield (Mints aUSDC 1:1 to this contract)
        aavePool.supply(address(usdcToken), _amount, address(this), 0);

        principalAmount += _amount;
        
        emit PrincipalDeposited(msg.sender, _amount);
    }

    /**
     * @dev Calculates the precise amount of yield generated by subtracting the locked 
     * principal from the dynamically growing aUSDC balance.
     */
    function getAvailableYield() public view returns (uint256) {
        uint256 currentBalance = aUsdcToken.balanceOf(address(this));
        if (currentBalance > principalAmount) {
            return currentBalance - principalAmount;
        }
        return 0;
    }

    /**
     * @dev Routes the generated APY directly to the Club Treasury. 
     * Anyone can call this to trigger the disbursement (automation friendly).
     */
    function harvestYield() external nonReentrant {
        uint256 yieldAmount = getAvailableYield();
        require(yieldAmount > 0, "No yield generated yet");

        // Transfer the aUSDC (yield) directly to the Club Treasury
        require(aUsdcToken.transfer(clubTreasuryWallet, yieldAmount), "Yield transfer failed");

        emit YieldHarvested(clubTreasuryWallet, yieldAmount);
    }

    /**
     * @dev Donor can unilaterally withdraw their principal at any time.
     * This withdraws the USDC from Aave and returns it strictly to the donor wallet.
     */
    function withdrawPrincipal(uint256 _amount) external onlyDonor nonReentrant {
        require(_amount > 0 && _amount <= principalAmount, "Invalid withdrawal amount");

        // Harvest any pending yield to the club first to ensure clean accounting
        uint256 pendingYield = getAvailableYield();
        if (pendingYield > 0) {
            aUsdcToken.transfer(clubTreasuryWallet, pendingYield);
            emit YieldHarvested(clubTreasuryWallet, pendingYield);
        }

        principalAmount -= _amount;

        // Withdraw USDC from Aave back to this contract
        aavePool.withdraw(address(usdcToken), _amount, address(this));

        // Transfer USDC strictly back to the Donor
        require(usdcToken.transfer(donorWallet, _amount), "Principal withdrawal failed");

        emit PrincipalWithdrawn(donorWallet, _amount);
    }
}
