import { initializeTracing } from "./instrumentation";

// Initialize tracing FIRST
initializeTracing();

// Fetch CSRF token once when app boots.
void initializeCsrf();

import React from "react";
import "./i18n";
import ReactDOM from "react-dom/client";
import { HelmetProvider } from "react-helmet-async";
import App from "./App";
import { BrowserRouter } from "react-router-dom";
import { CrossTabSyncProvider } from "./components/CrossTabSyncProvider";
import "./styles.css";
import { initOfflineCache } from "./lib/cache/offlineCache";
import { initOfflineSync } from "./lib/offlineSync";
import { initOfflineMutationQueue } from "./lib/offlineMutationQueue";
// @ts-expect-error - virtual:pwa-register is a virtual module generated by vite-plugin-pwa
import { registerSW } from "virtual:pwa-register";
import { initializeCsrf } from "./lib/csrf";
import { PresenceProvider } from "./hooks/usePresence";

// Start custom client-side caching layer with O(1) LRU eviction
initOfflineCache();
// Start background sync manager for offline event creation & replay
initOfflineSync();
// Start offline mutation queue manager for likes/RSVPs/bookmarks
initOfflineMutationQueue();

if ("serviceWorker" in navigator) {
  registerSW({ immediate: true });
}

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <HelmetProvider>
      <BrowserRouter>
        <CrossTabSyncProvider />
        <PresenceProvider>
          <App />
        </PresenceProvider>
      </BrowserRouter>
    </HelmetProvider>
  </React.StrictMode>,
);
