name: "13 PR Size Labeler"

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read
  issues: write

jobs:
  size-label:
    runs-on: ubuntu-latest

    steps:
      - name: Label pull request by size
        uses: codelytv/pr-size-labeler@v1
        with:
          xs_label: "size/XS"
          xs_max_size: "10"

          s_label: "size/S"
          s_max_size: "100"

          m_label: "size/M"
          m_max_size: "500"

          l_label: "size/L"
          l_max_size: "1000"

          xl_label: "size/XL"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}