name: Edge Function Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "supabase/functions/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Edge Function tests
        run: deno test --allow-env --allow-net --allow-read supabase/functions
